name: 'setup-emojicode'
description: 'Set up an Emojicode compiler on GitHub Actions'
author: 'Caleb Denio'
branding:
  icon: settings
  color: yellow
inputs:
  version:
    description: 'Emojicode version to download'
    required: false
    default: '1.0-beta.2'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/run.sh
      shell: bash
      env:
        EMOJI_VERSION: ${{ inputs.version }}
