name: 'Setup Emojicode'
description: 'Set up an Emojicode compiler on GitHub Actions'
inputs:
  version:
    description: 'Emojicode version to download'
    required: false
    default: '1.0-beta.2'
runs:
  using: "composite"
  steps:
    - run: ./run.sh
      shell: bash
